
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "playwright>=1.34.0",
    "requests>=2.31.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
